name: ki-demonstrator_wba_ima
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - click=7.0
  - flask=1.1.1
  - intel-openmp=2019.4
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - joblib=0.14.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - numpy=1.15.4
  - openssl=1.1.1c
  - pandas=0.25.1
  - pip=19.2.3
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.0
  - werkzeug=0.16.0
  - wheel=0.33.6
